//
//  GravityItemRecommendation.h
//  GravityClient
//
//  Created by Balazs Kiss on 7/8/13.
//  Copyright (c) 2013 Balazs Kiss. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 The list of items recommended to a user
 */
@interface GravityItemRecommendation : NSObject

/**
 The Id is generated by the recommendation engine
 */
@property NSString *Id;

/**
 The list of items
 */
@property NSArray *items;

/**
 The identifiers of the recommended items
 */
@property NSArray *itemIds;

/**
 The list of prediction values for the items
 */
@property NSArray *predictionValues;

/**
 Initializes a GravityItemRecommendation object with a dictionary
 @param dict the dictionary representing the object
 @return an initialized GravityItemRecommendation object
 */
- (id)initWithDictionary:(NSDictionary *)dict;

/**
 Initializes a GravityItemRecommendation object with JSON data
 @param jsonData the JSON data representing the object
 @return an initialized GravityItemRecommendation object
 */
- (id)initWithJSON:(NSData *)jsonData;

@end